# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"    \n"
"    background-color: rgb(57, 131, 177);\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid white\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 440, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setMouseTracking(True)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(79, 158, 218);\n"
"}")
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_object = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_object.setGeometry(QtCore.QRect(240, 230, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser_object.setFont(font)
        self.textBrowser_object.setStyleSheet("QTextBrowser{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px\n"
"}")
        self.textBrowser_object.setObjectName("textBrowser_object")
        self.textBrowser_data = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_data.setGeometry(QtCore.QRect(240, 320, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser_data.setFont(font)
        self.textBrowser_data.setStyleSheet("QTextBrowser{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px\n"
"}")
        self.textBrowser_data.setObjectName("textBrowser_data")
        self.textEdit_object = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_object.setGeometry(QtCore.QRect(240, 270, 321, 31))
        self.textEdit_object.setStyleSheet("QTextEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.textEdit_object.setObjectName("textEdit_object")
        self.textEdit_data = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_data.setGeometry(QtCore.QRect(240, 360, 321, 31))
        self.textEdit_data.setStyleSheet("QTextEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.textEdit_data.setObjectName("textEdit_data")
        self.textBrowser_folder = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_folder.setGeometry(QtCore.QRect(240, 50, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser_folder.setFont(font)
        self.textBrowser_folder.setStyleSheet("QTextBrowser{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px\n"
"}")
        self.textBrowser_folder.setObjectName("textBrowser_folder")
        self.textEdit_folder = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_folder.setGeometry(QtCore.QRect(240, 90, 321, 31))
        self.textEdit_folder.setStyleSheet("QTextEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.textEdit_folder.setObjectName("textEdit_folder")
        self.textEdit_excel = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_excel.setGeometry(QtCore.QRect(240, 180, 321, 31))
        self.textEdit_excel.setStyleSheet("QTextEdit{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.textEdit_excel.setObjectName("textEdit_excel")
        self.textBrowser_excel = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_excel.setGeometry(QtCore.QRect(240, 140, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textBrowser_excel.setFont(font)
        self.textBrowser_excel.setStyleSheet("QTextBrowser{\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px\n"
"}")
        self.textBrowser_excel.setObjectName("textBrowser_excel")
        self.pushButton_folder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_folder.setGeometry(QtCore.QRect(580, 90, 31, 31))
        self.pushButton_folder.setStyleSheet("QPushButton{\n"
"    background-color: rgb(79, 158, 218);\n"
"}")
        self.pushButton_folder.setObjectName("pushButton_folder")
        self.pushButton_excel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_excel.setGeometry(QtCore.QRect(580, 180, 31, 31))
        self.pushButton_excel.setStyleSheet("QPushButton{\n"
"    background-color: rgb(79, 158, 218);\n"
"}")
        self.pushButton_excel.setObjectName("pushButton_excel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Создать"))
        self.textBrowser_object.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Введите объект</span></p></body></html>"))
        self.textBrowser_data.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Введите дату</span></p></body></html>"))
        self.textBrowser_folder.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Выберите папку</span></p></body></html>"))
        self.textEdit_excel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_excel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\">Выберите документ excel</span></p></body></html>"))
        self.pushButton_folder.setText(_translate("MainWindow", "..."))
        self.pushButton_excel.setText(_translate("MainWindow", "..."))

